### ISSUE TITLE
Failed to activate the dev-tools-themes package

### ISSUE THREAD

**Issue by sadmicrowave** [travs/dev-tools-themes#10]
[Enter steps to reproduce:]

1. Start Atom
2. Enable dev-tools
3. Press F5 within devtools pane for refresh

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [dev-tools-themes](https://github.com/travs/dev-tools-themes) package 0.1.3

### Stack Trace

Failed to activate the dev-tools-themes package

```
At Could not call remote function 'anonymous'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from undefined

Error: Could not call remote function 'anonymous'. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from undefined
    at callFunction (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/browser/rpc-server.js:258:17)
    at ~/AppData/Local/atom/app-1.45.0/resources/electron.asar/browser/rpc-server.js:409:10
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
atom-console 0.4.6 
atom-html-preview 0.2.6 
atom-import-js 1.0.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
debug 0.0.1 
dev-tools-themes 0.1.3 
docblockr 0.13.7 
ide-html 0.6.0 
ide-python 1.5.0 
intentions 1.1.5 
jslint 1.5.1 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
native-ui 0.27.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
preview 0.19.0 
run-in-atom 1.0.5 
teletype 0.13.4 
todo-show 2.3.2 
web-data 0.7.1 
```

**Comment by travs** [comment]
Hey, thanks for reporting this. Unfortunately I don't have time to maintain this myself anymore, but if you are interested in digging into this and fixing it, I'd happily merge a PR.

I narrowed it down to (at least) this line being the cause: `bw.addDevToolsExtension(themePath);`
