### ISSUE TITLE
Cannot read property 'mainModulePath' of undefined

### ISSUE THREAD

**Issue by senpl** [travs/dev-tools-themes#9]
Failed to activate the dev-tools-dark package
Cannot read property 'mainModulePath' of undefined

[Enter steps to reproduce:] 1. ... 2. ... **Atom**: 1.18.0 x64 **Electron**: 1.3.15 **OS**: Ubuntu 16.04.1 **Thrown From**: [dev-tools-dark](https://github.com/agustif/dev-tools-dark) package 0.5.0 ### Stack Trace Failed to activate the dev-tools-dark package ``` At Cannot read property 'mainModulePath' of undefined TypeError: Cannot read property 'mainModulePath' of undefined at Object.activate (/packages/dev-tools-dark/lib/dev-tools-themes.js:57:69) at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25) at /usr/share/atom/resources/app/src/package.js:225:38 at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21) at /usr/share/atom/resources/app/src/package.js:218:32 at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40) at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40) at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:519:35 at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22) at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17) at /usr/share/atom/resources/app/src/buffered-process.js:359:17 at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15) at emitOne (events.js:101:20) at Socket.emit (events.js:188:7) at Pipe._handle.close [as _onclose] (net.js:493:12) ``` ### Commands ``` 2x -4:13 tree-view:show (atom-workspace.workspace.scrollbars-visible-always) -4:02.3.0 core:paste (input.hidden-input) 2x -3:53.9.0 dev-tools-themes:settingsView (input.hidden-input) -2:56.6.0 window:toggle-dev-tools (div.panels-item) -2:50.5.0 core:confirm (input.hidden-input) -1:05.8.0 dev-tools-themes:settingsView (a.) ``` ### Non-Core Packages ``` atom-autocomplete-php 0.25.6 atom-beautify 0.30.1 atom-runner 2.7.1 atom-shell-commands 1.5.0 dev-tools-dark 0.5.0 file-icons 2.1.7 git-control 0.9.0 language-groovy 0.7.0 node-debugger 1.10.1 php-debug 0.2.4 php-server 0.7.0 script 3.15.0 svn 0.0.13 tabs-to-spaces 1.0.3 trailing-spaces 0.4.0 turbo-javascript 1.4.0 xml-formatter 0.11.0 ```

**Comment by senpl** [comment]
Just after instalation it complain that atom was not up to date. But update not fix it. Uninstall and install package not helped.

**Comment by senpl** [comment]
it is https://github.com/agustif/dev-tools-dark/ issue but it direct to that site for issues. It was due to dev-tools-themes being not installed.
